.\"	$NetBSD$
.\"
.\" Copyright (c) 2008-2012 by Aleksey Cheusov (vle@gmx.net)
.\" Absolutely no warranty.
.\"
.\" ------------------------------------------------------------------
.de VB \" Verbatim Begin
.ft CW
.nf
.ne \\$1
..
.de VE \" Verbatim End
.ft R
.fi
..
.\" ------------------------------------------------------------------
.TH CVS_CHECKSUM 1 "Oct 28, 2012" "" ""
.SH NAME
cvs_checksum \- outputs checksums of CVS files
.SH SYNOPSIS
.BI cvs_checksum " [OPTIONS] [directories ...]"
.SH DESCRIPTION
.B cvs_checksum
analyses CVS files in the specified
.I directories
and outputs
checksums with a help of
.BR cksum(1) .
.SH OPTIONS
.TP
.B "-h"
Display help message.
.TP
.B "-l"
File revisions are output instead of checksums.
.SH ENVIRONMENT
.TP
.B CKSUM
Path to
.BR cksum(1) .
.SH EXAMPLES
.VB
cvs_checksum /usr/src/bin/sh
cvs_checksum -l /usr/pkgsrc/devel/libjudy /usr/pkgsrc/x11/xxkb
env CKSUM=md5 cvs_checksum /usr/src/bin/sh
.VE
.SH SEE ALSO
.BR cksum(1) ,
.B pkg_summary-utils(7)
.SH AUTHOR
Aleksey Cheusov <vle@gmx.net>
