.\"	$NetBSD$
.\"
.\" Copyright (c) 2008-2012 by Aleksey Cheusov (vle@gmx.net)
.\" Absolutely no warranty.
.\"
.\" ------------------------------------------------------------------
.de VB \" Verbatim Begin
.ft CW
.nf
.ne \\$1
..
.de VE \" Verbatim End
.ft R
.fi
..
.\" ------------------------------------------------------------------
.TH PKG_UPDATE_SRC_SUMMARY 1 "Oct 29, 2012" "" ""
.SH NAME
pkg_update_src_summary \- incrementally updates pkg_src_summary
.SH SYNOPSIS
.BI pkg_update_src_summary " [OPTIONS]"
.SH DESCRIPTION
.B pkg_update_src_summary
incrementally updates a summary information
for the specified source packages.
.SH OPTIONS
.TP
.B "-h"
Display help message.
.TP
.BI "-f" " filename"
Filename that contains PKGPATHs, one per line.
If not specified, summaries for packages returned by
.B pkg_list_all_pkgs(1)
are generated.
.TP
.BI "-i" " fields"
A list of fields (separated by space character or comma) to
generate. By default full summary is generated, see
.BR pkg_src_summary(1) .
.TP
.BI -d " datadir"
Directory where important files are stored,
this option is mandatory.
.SH ENVIRONMENT
.TP
.B PKGSRCDIR
Pkgsrc root directory.
.TP
.B BMAKE
Path to bmake.
.TP
.B PSS_OPTIONS
Options passed to
.B pkg_src_summary(1)
subprocesses.
.SH EXAMPLES
.VB
$ pkg_update_src_summary -d ~/src_summary

$ env PSS_OPTIONS=-m pkg_update_src_summary -d ~/src_summary

$ pkg_list_all_pkgs -a wip > ~/PKGPATHs
$ export PSS_OPTIONS=-m
$ pkg_update_src_summary -f ~/PKGPATHs -d ~/src_summary
.VE
.SH SEE ALSO
.BR pkg_summary-utils(7) ,
.BR pkg_src_summary(1),
.B pkg_list_all_pkgs(1)
.SH AUTHOR
Aleksey Cheusov <vle@gmx.net>
