.\"	$NetBSD$
.\"
.\" Copyright (c) 2017 by Aleksey Cheusov (vle@gmx.net)
.\" Absolutely no warranty.
.\"
.\" ------------------------------------------------------------------
.de VB \" Verbatim Begin
.ft CW
.nf
.ne \\$1
..
.de VE \" Verbatim End
.ft R
.fi
..
.\" ------------------------------------------------------------------
.TH PKG_CLEANUP_PACKAGES 1 "Feb 23, 2017" "" ""
.SH NAME
PKG_CLEANUP_PACKAGES \- cleanups PACKAGES directory
.SH SYNOPSIS
.BI pkg_cleanup_packages " [OPTIONS] [files ...]"
.SH DESCRIPTION
.B pkg_cleanup_packages
analyses FILE_NAME field of pkg_summary(5) given on input and
outputs list of files found in PACKAGES that are not referenced
by any package.
With option
.B "-r"
it removes all those files.
.SH OPTIONS
.TP
.BI "-s"
DIR is set as dirname of pkg_summary file. dirname is called as many times as
option
.B -s
is specified.
.TP
.B "-h"
Display help message.
.TP
.BI "-d " DIR
Directory to clean up. It overrides environment variable PACKAGES.
.TP
.BI "-r"
Remove unreferenced files.
.SH ENVIRONMENT
.TP
.B PACKAGES
Directory that contains distfiles. The default is /usr/pkgsrc/packages.
.TP
.B TMPDIR
Directory for temporary files, by default
.I /tmp
is used.
.SH EXAMPLES
.VB
export PACKAGES=/usr/pkgsrc/packages
pkg_cleanup_packages -r /usr/pkgsrc/packages/All/pkg_summary.txt
.VE
.SH SEE ALSO
.BR pkg_summary-utils(7) ,
.B pkg_summary(5)
.SH AUTHOR
Aleksey Cheusov <vle@gmx.net>
